config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: "home#index"
  get '/groups/product'
  resources :groups

  devise_for :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  # def index
  #   get 'index'
  # end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user
    @group.user_id = current_user.id
    @group.save
    redirect_to '/'
  end

  def show
    @group = Group.find(params[:id])
  end




  private

  def group_params
    params.require(:group).permit(:name, :price_limit, :no_users, :date)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @groups = Group.all
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  def new
    super
  end


  # POST /resource
  def create
    puts "HERE I AM $$$$$$$$$$$$$$$$$$$$$$"
    super
    if params(:group_id)
      add_new_users_to_groups(params(:group_id))
    end
  end

  private

  def add_new_users_to_groups
    @group = Group.find(params(:group_id))
    @group.users << current_user
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/index.html.erb
<a href="/groups/product.html">
  <img class="present" src='/ic_present.png'/ >
</a>

app/views/groups/new.html.erb
<!-- <%= form_for Group.new do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :How_many_guests? %>
 <%= f.text_field :no_users %>
 <%= f.text_field :email_four %>
 <%= f.label :How_much_should_we_spend? %>
 <%= f.text_field :price_limit %>
 <%= f.label :date %>
 <%= f.date_field :date %>
 <%= f.submit %>
<% end %> -->

<img src="pp.jpg">

app/views/groups/product.html.erb
<img src="/pp.jpg">

app/views/groups/show.html.erb
<h1> <%= @group.name %> </h1>
<h1> <%= @group.no_users %> </h1>
<h1> <%= @group.price_limit %> </h1>
<h1> <%= @group.date %> </h1>
<h1> <%= @group.user_id %> </h1>

app/views/home/index.html.erb
<!-- <% if user_signed_in? %> -->

    <h2 class="banner">161 days to go!</h2>
  <br>
  <div class="name">
    <h3> Your Secret Santa is</h3>
  <img class="profile_pic" src="/betty.jpg">
    <h1> Betty!</h1>
  </div>
  <p>Betty loves:</p>
  <label for="tag-typer">
  <div id="tags">
    <span class="tag"><span class="close">&times;</span>pets</span>
    <span class="tag"><span class="close">&times;</span>wine</span>
    <span class="tag"><span class="close">&times;</span>neck wear</span>
    <span class="tag"><span class="close">&times;</span>food</span>
    <br>
    <input id="tag-typer" type="text" placeholder="Anything else?"/>
  </div>
  </label>

  <div class="banner">
    <span style="width: 50%; text-align: center; margin-right: 30px" class="elf"><%= link_to "Elves' choice...", groups_path %></span>
    <span style="width: 50%; text-align: center"> Need some inspiration...?</span>
  </div>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<!-- <% else %> -->
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<!-- <% end %>  -->

app/views/home/show.html.erb
<img src="pp.jpg">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shhh!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
</head>
<body id="snow">
  <!-- <p class="notice"><%= notice %></p> -->
  <!-- <p class="alert"><%= alert %></p> -->
  <%= yield %>
</body>
</html>